core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.contrib import admin
from django.urls import path, include

from todo.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskToggleView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/toggle/", TaskToggleView.as_view(), name="task-toggle"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse("todo:tag-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def get_absolute_url(self):
        return reverse("todo:task-detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return f"{self.content} ({self.tags})"

todo/forms.py
from django import forms

from todo.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "content",
            "deadline",
            "done",
            "tags",
        ]
        widgets = {
            "deadline": forms.DateTimeInput(
                attrs={"type": "datetime-local", "class": "form-control"}
            ),
            "tags": forms.CheckboxSelectMultiple()
        }

todo/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404, redirect

from todo.models import Tag, Task
from todo.forms import TaskForm


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags").order_by("done", "-created_time")
    template_name = "todo/index.html"
    paginate_by = 4


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskToggleView(generic.View):
    @staticmethod
    def post(request, pk):
        task = get_object_or_404(Task, pk=pk)
        if task.done:
            task.done = False
        else:
            task.done = True
        task.save()
        return redirect("todo:index")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 10


class TagCreateView(generic.CreateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
    crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}
      {% endblock %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="{% url "todo:index" %}">Home page</a>
  </li>
  <li class="list-group-item">
    <a href="{% url "todo:tag-list" %}">Tags</a>
  </li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>TODO list <a class="btn btn-primary link-to-page" href="{% url "todo:task-create" %}">Add</a></h1>
  <br>
  {% if task_list %}
    <ul>
      {% for task in task_list %}
        <strong>{{ task.content }}</strong>
        <form  action="{% url "todo:task-toggle" task.id %}" method="post">
          {% csrf_token %}
          {% if task.done %}
            <strong style="color: green;">Done</strong>
            <input class="btn btn-secondary link-to-page" type="submit" value="Undo">
          {% else %}
            <strong style="color: red;">Not done</strong>
            <input class="btn btn-success link-to-page" type="submit" value="Complete">
          {% endif %}
        </form>
        <br>
        <p>
          Created: {{ task.created_time }}
          {% if task.deadline %}
            <b style="color: darkred;">Dealine: {{ task.deadline }}</b>
          {% endif %}
        </p>
        <p>
          {% if task.tags.all %}
          Tags:
            {% for tag in task.tags.all %}
              {{ tag }}
            {% endfor %}
          {% else %}
          No tags
          {% endif %}
          <a href="{% url "todo:task-update" task.id %}">Update</a>
          <a href="{% url "todo:task-delete" task.id %}">Delete</a>
        </p>
        <hr>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
	<h1>Delete tag</h1>
	<p>{{ tag }}</p>
	<form action="" method="post">
		{% csrf_token %}
		<input type="submit" value="Delete" class="btn btn-danger">
		<a href="{% url "todo:tag-list" %}" class="btn btn-primary">Cancel</a>
	</form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="{{ object|yesno:"Update,Create" }}">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags <a class="btn btn-primary link-to-page" href="{% url "todo:tag-create" %}">Add</a></h1>
  <br>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a class="btn btn-secondary" href="{% url "todo:tag-update" tag.id %}">Update</a></td>
          <td><a class="btn btn-danger" href="{% url "todo:tag-delete" tag.id %}">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p><strong>No tags!</strong></p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
	<h1>Delete task</h1>
	<p>{{ task.content }}</p>
	<form action="" method="post">
		{% csrf_token %}
		<input type="submit" value="Delete" class="btn btn-danger">
		<a href="{% url "todo:index" %}" class="btn btn-primary">Cancel</a>
	</form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="{{ object|yesno:"Update,Create" }}">
  </form>
{% endblock %}